### ISSUE TITLE
the counter maybe off

### ISSUE THREAD

**Issue by francislee** [commadelimited/jQuery-Mobile-Tiny-Sort#3]
Nice plug in, but I notice that count is not exactly matched to the total number of listitem.

**Comment by commadelimited** [comment]
@francislee can you be a little more clear? Perhaps you can provide an example?

**Comment by francislee** [comment]
Hi Andy,

Here is an example as attached, it got 5 items in the list but the counter
just show 4. I also found out if a link to this page was using AJAX then
the sorting menu won't show up in the first load. Do you have any solution
for it?

Thanks,

**Comment by commadelimited** [comment]
@francislee you forgot the attachment

**Comment by francislee** [comment]
Hi Andy,

I did attached on the email. I guess the attachment may not able to show to
GitHub.

Here is the link to example on google drive
https://drive.google.com/#folders/0B4-FdyfiaFtpc1VDNWJNZ1pQSlE

Thanks,

**Comment by commadelimited** [comment]
Okay. I'll take a look.

**Comment by commadelimited** [comment]
Oh, it's just a standalone file. Is there any way I could see this page in the context of your app? When I download that file all of the external resources are broken.

**Comment by francislee** [comment]
Hi Andy,

I just uploaded a zip file.

Thanks,

**Comment by commadelimited** [comment]
@francislee sorry about the delay in this. Turns out my logic had a bug where the count was always going to be off by one. Oops. This fixes it and adds a unit test to check for it in the future.
